### ISSUE TITLE
Cannot startup using docker-compose

### ISSUE THREAD

**Issue by githara** [efkbook/blog-sample#27]
I've downloaded your sample code and tried to startup using the `docker-compose` command, but I am seeing errors and can't figure out what's wrong.

My environment:
- MacBook Pro High Sierra v10.13.1（17B1002）

The command I've used:
`docker-compose up -d`

The error I see in the terminal:
> Building fluentd
> Step 1/7 : FROM debian:jessie
>  ---> 25fc9eb3417f
> Step 2/7 : ENV DEBIAN_FRONTEND noninteractive
>  ---> Using cache
>  ---> 3a1b64603c5c
> Step 3/7 : RUN apt-get -qq update && apt-get install --no-install-recommends -y curl ca-certificates sudo
>  ---> Using cache
>  ---> f7d405eb6fb1
> Step 4/7 : RUN curl -L https://toolbelt.treasuredata.com/sh/install-debian-jessie-td-agent2.sh | sh
>  ---> Using cache
>  ---> 20b288bcc2d4
> Step 5/7 : RUN /usr/sbin/td-agent-gem install fluent-plugin-elasticsearch fluent-plugin-record-reformer
>  ---> Running in 65eb3b5c7c61
> Successfully installed serverengine-2.0.5
> Building native extensions.  This could take a while...
> ERROR:  Error installing fluent-plugin-elasticsearch:
>         ERROR: Failed to build gem native extension.
> 
>     current directory: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/strptime-0.1.9/ext/strptime
> /opt/td-agent/embedded/bin/ruby -r ./siteconf20171202-7-edjo8s.rb extconf.rb
> checking for rb_timespec_now()... *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
>         --with-opt-dir
>         --with-opt-include
>         --without-opt-include=${opt-dir}/include
>         --with-opt-lib
>         --without-opt-lib=${opt-dir}/lib
>         --with-make-prog
>         --without-make-prog
>         --srcdir=.
>         --curdir
>         --ruby=/opt/td-agent/embedded/bin/ruby
> /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
> You have to install development tools first.
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:552:in `try_link0'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:567:in `try_link'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:747:in `try_func'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:1032:in `block in have_func'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:923:in `block in checking_for'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:922:in `checking_for'
>         from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:1031:in `have_func'
>         from extconf.rb:3:in `<main>'
> 
> To see why this extension failed to compile, please check the mkmf.log which can be found here:
> 
>   /opt/td-agent/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/strptime-0.1.9/mkmf.log
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/strptime-0.1.9 for inspection.
> Results logged to /opt/td-agent/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/strptime-0.1.9/gem_make.out
> Successfully installed fluent-plugin-record-reformer-0.9.1
> Parsing documentation for fluent-plugin-record-reformer-0.9.1
> Installing ri documentation for fluent-plugin-record-reformer-0.9.1
> Done installing documentation for fluent-plugin-record-reformer after 0 seconds
> 1 gem installed
> ERROR: Service 'fluentd' failed to build: The command '/bin/sh -c /usr/sbin/td-agent-gem install fluent-plugin-elasticsearch fluent-plugin-record-reformer' returned a non-zero code: 1

**Comment by koetsuserizawa** [comment]
👍 same here.
Error message I got below:

```
Step 5/7 : RUN /usr/sbin/td-agent-gem install fluent-plugin-elasticsearch fluent-plugin-record-reformer
 ---> Running in c9d5af60a291
Building native extensions.  This could take a while...
Successfully installed msgpack-1.3.3
Successfully installed serverengine-2.2.1
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-elasticsearch:
	fluentd requires Ruby version >= 2.4.
Successfully installed strptime-0.2.3
Successfully installed fluent-plugin-record-reformer-0.9.1
Parsing documentation for fluent-plugin-record-reformer-0.9.1
Installing ri documentation for fluent-plugin-record-reformer-0.9.1
Done installing documentation for fluent-plugin-record-reformer after 0 seconds
1 gem installed
ERROR: Service 'fluentd' failed to build: The command '/bin/sh -c /usr/sbin/td-agent-gem install fluent-plugin-elasticsearch fluent-plugin-record-reformer' returned a non-zero code: 1
```

Now I guess that installing `fluent-plugin-elasticsearch` might require ruby on debian.

**Comment by kou01171031** [comment]
+ 1
